"""update relationships

Revision ID: 2174682b733e
Revises: 656748f99bcb
Create Date: 2023-06-14 14:42:06.204753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2174682b733e'
down_revision = '656748f99bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint('fk_activities_day_id_days', type_='foreignkey')
        batch_op.drop_column('day_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_activities_day_id_days', 'days', ['day_id'], ['id'])

    # ### end Alembic commands ###
