"""added date to activities

Revision ID: 54131ea2a353
Revises: d93b236be711
Create Date: 2023-06-18 19:17:36.813079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54131ea2a353'
down_revision = 'd93b236be711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
