"""updating db models

Revision ID: 656748f99bcb
Revises: 719e871ed135
Create Date: 2023-06-14 14:28:11.871057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656748f99bcb'
down_revision = '719e871ed135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint('fk_activities_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_activities_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
