"""removed days model

Revision ID: c995b52934e5
Revises: 2174682b733e
Create Date: 2023-06-14 15:10:22.693935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c995b52934e5'
down_revision = '2174682b733e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('days')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_activities_trip_id_trips'), 'trips', ['trip_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_activities_trip_id_trips'), type_='foreignkey')
        batch_op.drop_column('trip_id')

    op.create_table('days',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('trip_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name='fk_days_trip_id_trips'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
